In [3]:
import numpy as np

In [4]:
# Question 1:

arr = np.array(np.random.normal(0,1,25))
print(arr)

[-0.88973859 -0.50962706  0.24242288 -0.41278082 -0.09601765 -0.10458897
  0.35048734  1.23581404 -0.03766339 -0.42161241 -0.82346365 -0.24454025
 -0.64355789  0.45586851  0.49598854 -1.25347666 -2.10848157  0.6522203
  0.67180471  1.43614051 -0.9257663  -0.99271009  0.28577388  0.93857504
 -1.6003306 ]


In [5]:
# Question 2:

n = 20
arr2 = np.array(np.arange(0,1,1/n))
print(arr2)

[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95]


In [6]:
# Question 3:
n = 5
arr3 = np.array([[n*j+i+1 for i in range(n)] for j in range(n)])
print(arr3)

# 1:
std_dev = np.std([arr3])
print("Standard deviation of whole matrix is:\n",std_dev)
std_c = np.std(arr3,axis=0)
std_r = np.std(arr3,axis=1)
print("Standard deviation of columns of matrix is:\n", std_c)
print("Standard deviation of rows of matrix is:\n", std_r)

# 2:
print("Sum of all columns is:\n", np.sum(arr3,axis=0))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Standard deviation of whole matrix is:
 7.211102550927978
Standard deviation of columns of matrix is:
 [7.07106781 7.07106781 7.07106781 7.07106781 7.07106781]
Standard deviation of rows of matrix is:
 [1.41421356 1.41421356 1.41421356 1.41421356 1.41421356]
Sum of all columns is:
 [55 60 65 70 75]


In [7]:
# Question 4:

X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
print(X)

d = np.diagonal(X)
print("Diagonal of X is:\n",d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Diagonal of X is:
 [ 0  5 10]


In [8]:
# Question 5:

p = np.diagflat([1, 2, 3, 4])
print(p)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [9]:
# Question 6:

array = np.array([[ 1, 2, 3], [ 4, 5, 6], [ 7, 8, 9], [ 10, 11, 12]])
print(array)

array = np.triu(array,-1)
print(array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 0  8  9]
 [ 0  0 12]]


In [10]:
# Question 7:

a = np.arange(100,200,10)
a = a.reshape(5,2)
print(a)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [11]:
# Question 8:

def check(value, array):
  if value in array:
    return True
  return False

print(arr3)
print(check(15,arr3))
print(check(27,arr3))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
True
False


In [12]:
# Question 9:

def diagonal_sum(array):
  return np.diagonal(array).sum()

print(arr3)
print("Sum of diagonal elements is:" ,diagonal_sum(arr3))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Sum of diagonal elements is: 65


In [13]:
# Question 10:

def determinant(array):
  return np.linalg.det(array)

array123 = np.array([[ 1, 2, 3], [ 4, 5, 6], [ 0, 8, 9]])
print(array123)
print("Determinant of above matrix is: ", determinant(array123))

[[1 2 3]
 [4 5 6]
 [0 8 9]]
Determinant of above matrix is:  20.99999999999999


In [14]:
# Question 11:

arr1 = np.array([1, 2, 3, 4, 5])

arr2 = np.array([2, 2, 4, 4, 6])

greater = np.greater(arr1, arr2)
print("Greater:", greater)

greater_equal = np.greater_equal(arr1, arr2)
print("Greater Equal:", greater_equal)

less = np.less(arr1, arr2)
print("Less:", less)

less_equal = np.less_equal(arr1, arr2)
print("Less Equal:", less_equal)


Greater: [False False False False False]
Greater Equal: [False  True False  True False]
Less: [ True False  True False  True]
Less Equal: [ True  True  True  True  True]


In [15]:
# Question 12:

array = np.zeros((10,10))
print(array)


def border(array):
  for i in range(np.shape(array)[0]):
    for j in range(np.shape(array)[1]):
      if i in (0,np.shape(array)[0]-1) or j in (0,np.shape(array)[1]-1):
        array[i][j] = 1
  return array

print("\nChanging border enteries to 1:")
print(border(array))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

Changing border enteries to 1:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
# Question 1:

a = np.random.randint(50, 100, size=(5, 10))
print(a)

[[72 86 69 74 64 64 70 73 95 71]
 [61 72 64 71 95 77 69 87 65 86]
 [75 95 59 96 99 88 57 72 60 50]
 [55 60 82 73 67 97 52 89 71 66]
 [81 62 76 87 95 76 69 97 75 82]]


In [17]:
# Question 2:

b = np.random.uniform(50, 101, size=(5, 10)).round(2)
print(b)


[[ 81.84  86.46  75.84  92.83  89.6   98.99  79.01  61.15  92.58  68.87]
 [ 55.7   50.15  86.3   76.08  53.3   82.97  58.28 100.38  54.86  86.11]
 [ 75.35  65.03  84.6   54.56  70.96  80.39  69.27  73.6   77.53  60.88]
 [ 66.61  93.1   53.4   61.1   91.6   67.16  61.09 100.92  63.42  94.49]
 [ 86.29  60.2   72.36  69.87  82.68  67.56  55.87  81.69 100.52  91.14]]


In [18]:
# Question 3:

array_i = np.array([i for i in range(2,100) if 2**i % 10 == 6])
print(array_i)

[ 4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92 96]


In [19]:
# Question 4:

array_2_powers = np.array([2**i for i in range(1,11)])
print(array_2_powers)


[   2    4    8   16   32   64  128  256  512 1024]


In [20]:
# Question 5:

arr = np.array([[10*j+i for i in range(6)] for j in range(6)])
print(arr)

print("\n1:")
print(arr[0][3],arr[0][4])

print("\n2:")
col = np.array([arr[i][2] for i in range(6)])
print(col)

print("\n3:")
two = np.array([arr[2],arr[4]])
#two = np.array([[arr[i][j] for j in range(0,6,2)] for i in (2,4)])
print(two)

print("\n4:")
print(arr[3][3])

print("\n5:")
new = np.array([[arr[i][j] for j in (4,5)] for i in (4,5)])
print(new)


[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]

1:
3 4

2:
[ 2 12 22 32 42 52]

3:
[[20 21 22 23 24 25]
 [40 41 42 43 44 45]]

4:
33

5:
[[44 45]
 [54 55]]
